---
- name: CI Pipeline
  become: True
  hosts: builder
  gather_facts: False
  vars:
    git_repo: 'git.uns.co/InformationServices/tep_dc.git'
    git_branch: 'main'
    build_dir: '/tmp/tep_dc_build'
    galaxy_hub: 'tusldanshub01.unisource.corp'
    collection_namespace: 'tep'
    collection_name: 'dc'
    collection_version: '1.0.1'

  tasks:
    - name: Build and publish collection
      block:
      - name: Install dependencies
        ansible.builtin.package:
          name:
            - git
            - ansible-core
            - ansible-builder
            - python3-devel
          state: present
        tags: setup

      - name: Set vars
        set_fact: 
          git_url: 'https://{{ git_user| urlencode }}:{{ git_pass | urlencode }}@{{ git_repo }}'
      
      - name: Clone repo
        ansible.builtin.git:
          repo: "{{ git_url }}"
          dest: "{{ build_dir }}"
          version: "{{ git_branch }}"
          force: yes
      
      - name: Build collection
        ansible.builtin.command:
          cmd: ansible-galaxy collection build --force
          chdir: "{{ build_dir }}"
        register: build_result
        failed_when: build_result.rc != 0
      
      - name: Publish collection
        ansible.builtin.command:
          cmd: ansible-galaxy collection publish {{ build_dir }}/{{ collection_namespace }}-{{ collection_name }}-{{ collection_version }}.tar.gz -s https://{{ galaxy_hub }}/api/galaxy --api-key {{ galaxy_api_key }}
          chdir: "{{ build_dir }}"
        tags: publish
        register: publish_result
        failed_when: Collection has been successfully published not in publish_result.stdout
      
      - name: Build execution environment
        ansible.builtin.command:
          cmd: ansible-builder build --tag {{ galaxy_hub }}/tep_dc
          chdir: "{{ build_dir }}/meta"

      always:
        - name: Clean up
          ansible.builtin.file:
            name: "{{ build_dir }}"
            state: absent
          tags: cleanup
